### ISSUE TITLE
Can you share the earth quake data in the example?

### ISSUE THREAD

**Issue by xichaoqiang** [ColinLii/CC-FJpy#1]
Hello, Dr Li.

Thanks for sharing this great package about FJ algorithm. This package is very well written. Really a great Job.

Your presentation in  CGU Chongqing is also very impressive. 

Now I also do some research about FJ transform with Hankel function, which has been accepted by GJI.

Can you share me the earth quake data in the example for study?

Thanks very much.

Best regards,
Xi

**Comment by ColinLii** [comment]
Hello, Dr Xi,
Thank you very much for concerning our work.

I will upload the earthquake data after the Spring Festival holiday. 

I am going to read your GJI paper after the Spring Festival holiday.

Thank you for your suggestion.

If you have any other suggestions, comments or questions, do not hesitate to contact us.

Best regards,
Zhengbo Li

**Comment by xichaoqiang** [comment]
Thanks for your reply.I think I can close this issue.
