### ISSUE TITLE
Run isssue about ccfj

### ISSUE THREAD

**Issue by xichaoqiang** [ColinLii/CC-FJpy#2]
Hello Dr Li

I try install CCFJ on my workstaion (Ubuntu) and personal virtual maichine (Centos). I meet two problem, and now I only fix one.

1. After install CPU version of CCFJ, I try import ccfj, an error message shows  "undefined symbol: omp_get_thread_num"
I add ' '-fopenmp''  In steupCPU.py ''  line31,  it seems work well now.
linkerargs = ['-Wl,-rpath,lib', '-fopenmp']

2. I try run example_noise.ipynb, but the ipython kernel will restart in the third block. Both CPU and GPU versions can't work. 

![图片](https://user-images.githubusercontent.com/30900789/108614309-4afabd80-7434-11eb-9e7c-ded1f12e1814.png)

**Comment by ColinLii** [comment]
Thank you, Dr Xi,

Appreciate for your feedbacks.

For the first one, the problem may be caused by the different version of openMP. Thus, we reserved an interface to uncompiler the function of openMP, just as you have fixed (delete the '-DuseOMP' option). In the future, we will check the interface of different version of openMP. In addition, the openMP we used is the openMP in gcc-4.8.5 installed on CentOS 7.

For the second one, we will check this problem as soon as possible.  After getting your feedback, we also found this problem on some machines.   It may be because there are some bugs where the core C functions and Python match.  In rewritten part of interfaces in this packaging. Anyway, we will fix this problems and upload the earthquake data you requested last time as soon as possible.

Best regards,

Zhengbo Li

**Comment by xichaoqiang** [comment]
Thanks for you reply.  @ColinLii

**Comment by ColinLii** [comment]
Hello, Dr Xi,
We found that although sometimes the jupyter kernel crushed, the .py script works well. Thus we upload the .py script and the earthquake data you requested. Please try the .py script again. 

We will continue to find the reason of jupyter kernel crushing.

Sorry for this problem.

Have a great day,

Zhengbo Li

**Comment by xichaoqiang** [comment]
That's great.Thanks.

**Comment by xichaoqiang** [comment]
It seems that both two .py files can't run.

![图片](https://user-images.githubusercontent.com/30900789/108941094-70373800-768f-11eb-9451-48248923fd34.png)

![图片](https://user-images.githubusercontent.com/30900789/108941195-9fe64000-768f-11eb-91cb-1a99d0061fb2.png)

**Comment by ColinLii** [comment]
It runs well in our server.

We will check it on other machines.

Thank you for telling us this information.

![run](https://user-images.githubusercontent.com/15098745/108942146-657da280-7691-11eb-9f37-fe3cd6bf5f08.PNG)

**Comment by ColinLii** [comment]
Since you run on virtual machine, we guess that you are running the CPU version. 

Can you confirm which version you are using and test another version?

We need to confirm which version has this kind of problem.

Thanks a lot.

**Comment by ColinLii** [comment]
Since you run on virtual machine, we guess that you are running the CPU version. 

Can you confirm which version you are using and test another version?

We need to confirm which version has this kind of problem.

Thanks a lot.

**Comment by xichaoqiang** [comment]
Both installed version is CPU version @ColinLii

**Comment by ColinLii** [comment]
Thank you, 

We just tested the GPU version, I think the problem may be the CPU version, we will fix it as soon as possible.

@xichaoqiang

**Comment by xichaoqiang** [comment]
This is error message of GPU version.

![image](https://user-images.githubusercontent.com/30900789/108943182-4718a680-7693-11eb-924d-c1065b0de295.png)

**Comment by xichaoqiang** [comment]
Here is my Cuda version information.
![image](https://user-images.githubusercontent.com/30900789/108943688-4fbdac80-7694-11eb-915e-c3147d858c89.png)

**Comment by ColinLii** [comment]
This Error seems that the there are some problems for gpu to allocate global memory. 

It seems that gpu 0 (default gpu) does not have enough global memory for allocating.  Maybe you can try it later after the program running on gpu 0 releases the memory. Or we will update a new version which allow you to choose GPU.

Thank you telling us this information.

**Comment by ColinLii** [comment]
Please note that it needs about 200 MB GPU global memory for the example of noise.

**Comment by xichaoqiang** [comment]
Thanks for your reply.The examples of  GPU version seems works well.

![图片](https://user-images.githubusercontent.com/30900789/108947209-fb69fb00-769a-11eb-95de-c84f9eb1ce7f.png)

![图片](https://user-images.githubusercontent.com/30900789/108947301-2c4a3000-769b-11eb-928b-ead70b819c13.png)

**Comment by ColinLii** [comment]
OK, we will try to fix the problems of CPU version as soon as possible.

**Comment by xichaoqiang** [comment]
Thanks you.Really a good job.

**Comment by xichaoqiang** [comment]
Both ipynb of GPU version can works well. But the path of datafile in example_EQ.ipynb should also need change.

**Comment by ColinLii** [comment]
Thanks for the reminder, we have made a modification.

**Comment by ColinLii** [comment]
@xichaoqiang Hello, Dr Xi,

We think that the cpu version can work. Also the setup of openmp is modified.

Thank you again!

**Comment by ColinLii** [comment]
In addition, we add a new parameter to control the number of threads of CPU version and device number of GPU version.

**Comment by xichaoqiang** [comment]
Thanks. The CPU version can run on the both workstation and virtual machine now.
Really NB.

![图片](https://user-images.githubusercontent.com/30900789/109158697-addeb280-77ae-11eb-8b57-3051e1f074c3.png)

**Comment by xichaoqiang** [comment]
Dear Dr Li, I think this issue can be close now.
