### ISSUE TITLE
some issue about ccfj installation

### ISSUE THREAD

**Issue by Stuxuk** [ColinLii/CC-FJpy#4]
hello Dr.Li
![1a99dca980fd3a929af4beecbd495c4e](https://github.com/user-attachments/assets/54e9400d-cdcc-4c6e-af23-071f5eb61993)
I followed your tutorial to install ccfj, but ran into some problems:
1. Following the tutorial configuration, a g++ error is displayed
2. I suspect the problem is GPU, so I tried to install only the cpu version, but No error was reported during installation, but import ccfj showed No module named ccfj
I don't know what the reason is. I hope you can help me solve it. Thank you very much！

**Comment by Hanwu-pku** [comment]
I have the issue too.
How do you solve this issue？
Thanks for your answer.
